# Generated by Django 5.2 on 2026-10-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_purchase_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='affiliate_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Comisión asignada al afiliado', max_digits=10),
        ),
        migrations.AddField(
            model_name='purchase',
            name='instructor_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Ganancia neta para el creador del curso', max_digits=10),
        ),
        migrations.AddField(
            model_name='purchase',
            name='platform_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='20% retenido por CrearVende', max_digits=10),
        ),
    ]
